name: Process .prp files

on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
  
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # with:
      #    ref: "main" # uncomment this line to check out a specific branch
      - name: Update variables
        uses: CIFriends/prp-preprocessor@v1
        env:
          motto: "Making your CI/CD experience smoother, friendlier, and more efficient."
